# Generated by Django 5.1.1 on 2025-09-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_options_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Одобрен ли комментарий модератором', verbose_name='Одобрен'),
        ),
    ]
